#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/e4a42b1e-aa0d-4676-bf44-ded1bc4a8ac7 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int moisture;
  bool motorState;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  Serial.println("Initialising");
  pinMode(D1, OUTPUT);
  pinMode(A0, INPUT);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  moisture = analogRead(A0);  //soil sensor sensor reads the value of moisture
  moisture = map(moisture, 1024, 0, 0, 100);
  Serial.print(moisture);
  Serial.println(" %");
  if (moisture < 10) {
    digitalWrite(1, HIGH);
    motorState = true;
    Serial.println("motor on ");
  } else {
    digitalWrite(1, LOW);
    motorState = false;
    Serial.println("motor off");
  }
  delay(500);
}




/*
  Since Moisture is READ_WRITE variable, onMoistureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMoistureChange() {
  // Add your code here to act upon Moisture change
}

/*
  Since MotorState is READ_WRITE variable, onMotorStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotorStateChange() {
  // Add your code here to act upon MotorState change
}