// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "727cc53a-b42f-49d4-b174-f3d983450f0f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMoistureChange();
void onMotorStateChange();

int moisture;
bool motorState;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(moisture, READWRITE, ON_CHANGE, onMoistureChange);
  ArduinoCloud.addProperty(motorState, READWRITE, ON_CHANGE, onMotorStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
